version: '3.9'

services:

  db:
    image: postgres:12.20-alpine3.20
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}