version: '3.9'

services:

  db:
    image: mysql:8.2.0
    container_name: db_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db_test
    volumes:
      - ./db-data:/var/lib/mysql